// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvaV_AireuXQwSeEXwgVbezKbiXLfGhPM',
    appId: '1:861066208446:android:6f324b27d25505a89daaef',
    messagingSenderId: '861066208446',
    projectId: 'tcc-app-acr',
    storageBucket: 'tcc-app-acr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6QgKcvmEkzOR2TKokPSiUhmdcecBzLg',
    appId: '1:861066208446:ios:ae5f3f70dba244fb9daaef',
    messagingSenderId: '861066208446',
    projectId: 'tcc-app-acr',
    storageBucket: 'tcc-app-acr.appspot.com',
    iosClientId: '861066208446-9q14mloebu6qtm1fn1k7etkn2tc28kfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccApp',
  );
}
